# Generated by Django 3.2.13 on 2022-05-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userworkapp', '0001_initial'),
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_authors',
        ),
        migrations.AddField(
            model_name='project',
            name='project_authors',
            field=models.ManyToManyField(to='userworkapp.User'),
        ),
    ]
